version: '3.5'
services:
  app:
    build:
      context: .
    environment:
      - MIX_ENV=dev
      - YOUTUBE_API_KEY=AIzaSyCplYpZgrQ_no84WG5_L3uWagcRv3jn71s
    networks:
      memorex-exposed:
      memorex-api:
        aliases:
          - memorex-playlist-api
    ports:
      - "4004:4000"
    volumes:
      - type: bind
        source: .
        target: /usr/src/app
      - type: volume
        source: _build
        target: /usr/src/app/_build
        volume:
          nocopy: true
      - type: volume
        source: deps
        target: /usr/src/app/deps
        volume:
          nocopy: true
networks:
  memorex-exposed:
    driver: bridge
    name: memorex-exposed
  memorex-api:
    driver: bridge
    name: memorex-api
    internal: true
volumes:
  _build:
  deps:
